/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

/**
 *
 * @author umadh
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        logoutbtn = new javax.swing.JButton();
        viewbtn1 = new javax.swing.JButton();
        addstudentbtn = new javax.swing.JButton();
        addcontactbtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2024-06-13 000454.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtn.setBackground(new java.awt.Color(51, 51, 51));
        logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 0));
        logoutbtn.setText("LOGOUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        viewbtn1.setBackground(new java.awt.Color(51, 51, 51));
        viewbtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewbtn1.setForeground(new java.awt.Color(255, 255, 0));
        viewbtn1.setText("VIEW");
        viewbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(viewbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        addstudentbtn.setBackground(new java.awt.Color(51, 51, 51));
        addstudentbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addstudentbtn.setForeground(new java.awt.Color(255, 255, 0));
        addstudentbtn.setText("ADD STUDENT DETAILS");
        addstudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addstudentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        addcontactbtn.setBackground(new java.awt.Color(51, 51, 51));
        addcontactbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addcontactbtn.setForeground(new java.awt.Color(255, 255, 0));
        addcontactbtn.setText("ADD CONTACT DETAILS");
        addcontactbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcontactbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addcontactbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 0));
        jTextField1.setText("STUDENT MANAGEMENT SYSTEM");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 610, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2024-06-13 000454.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1060, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtn1ActionPerformed
        details m1 = new details();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewbtn1ActionPerformed

    private void addstudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentbtnActionPerformed
        main m1 = new main();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addstudentbtnActionPerformed

    private void addcontactbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcontactbtnActionPerformed
        parent m1 = new parent();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addcontactbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
      login m1 = new login();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcontactbtn;
    private javax.swing.JButton addstudentbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton viewbtn1;
    // End of variables declaration//GEN-END:variables
}
